"""Easing Lab public library API."""

from .core import (
    FORMAT_NAME,
    FORMAT_VERSION,
    PRESETS,
    CubicSegment,
    Curve,
    EasingFunction,
    InvalidCurveError,
    Preset,
    back_in_out,
    bounce_in_out,
    bounce_out,
    clamp,
    clamp01,
    cubic_in_out,
    curve_from_preset,
    easing_from_dict,
    elastic_in_out,
    evaluate,
    interpolate,
    linear,
    load_easing,
    ping_pong,
    preset_document,
    quint_in_out,
    resolve_easing,
    sine_in_out,
    smootherstep,
    smoothstep,
)

__version__ = "0.1.0"

__all__ = [
    "FORMAT_NAME",
    "FORMAT_VERSION",
    "PRESETS",
    "CubicSegment",
    "Curve",
    "EasingFunction",
    "InvalidCurveError",
    "Preset",
    "__version__",
    "back_in_out",
    "bounce_in_out",
    "bounce_out",
    "clamp",
    "clamp01",
    "cubic_in_out",
    "curve_from_preset",
    "easing_from_dict",
    "elastic_in_out",
    "evaluate",
    "interpolate",
    "linear",
    "load_easing",
    "ping_pong",
    "preset_document",
    "quint_in_out",
    "resolve_easing",
    "sine_in_out",
    "smootherstep",
    "smoothstep",
]
